### ISSUE TITLE
Add text-only interaction mode

### ISSUE THREAD

**Issue by Xyaneon** [WarriorIng64/LTUAssistant#10]
We should add a command line switch which will allow us to run the assistant in a text-only mode, with no speaking or sound necessary. This will let us test interactive conversations, like setting up a calendar event, more easily by just using the terminal, or skip trying to get Google to transcribe speech if it's not available for some reason.

**Comment by Xyaneon** [comment]
I plan on approaching this by using Python's excellent [`argparse`](https://docs.python.org/2.7/library/argparse.html) built-in module.

**Comment by Xyaneon** [comment]
This is being implemented by me in the [`text-only-mode`](https://github.com/WarriorIng64/LTUAssistant/tree/text-only-mode) branch.

**Comment by jacob1** [comment]
I was using this command previously: python -i -c "from integrated import Integrate"

But I don't think that will work with your calendar events so that sounds good.
